// @ts-check
const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const countries = [
  { isoCode: 'AF', name: 'Afghanistan', capital: 'Kabul' },
  { isoCode: 'AL', name: 'Albania', capital: 'Tirana' },
  { isoCode: 'DZ', name: 'Algeria', capital: 'Algiers' },
  { isoCode: 'AD', name: 'Andorra', capital: 'Andorra la Vella' },
  { isoCode: 'AO', name: 'Angola', capital: 'Luanda' },
  { isoCode: 'AG', name: 'Antigua and Barbuda', capital: "Saint John's" },
  { isoCode: 'AR', name: 'Argentina', capital: 'Buenos Aires' },
  { isoCode: 'AM', name: 'Armenia', capital: 'Yerevan' },
  { isoCode: 'AU', name: 'Australia', capital: 'Canberra' },
  { isoCode: 'AT', name: 'Austria', capital: 'Vienna' },
  { isoCode: 'AZ', name: 'Azerbaijan', capital: 'Baku' },
  { isoCode: 'BS', name: 'Bahamas', capital: 'Nassau' },
  { isoCode: 'BH', name: 'Bahrain', capital: 'Manama' },
  { isoCode: 'BD', name: 'Bangladesh', capital: 'Dhaka' },
  { isoCode: 'BB', name: 'Barbados', capital: 'Bridgetown' },
  { isoCode: 'BY', name: 'Belarus', capital: 'Minsk' },
  { isoCode: 'BE', name: 'Belgium', capital: 'Brussels' },
  { isoCode: 'BZ', name: 'Belize', capital: 'Belmopan' },
  { isoCode: 'BJ', name: 'Benin', capital: 'Porto-Novo' },
  { isoCode: 'BT', name: 'Bhutan', capital: 'Thimphu' },
  { isoCode: 'BO', name: 'Bolivia', capital: 'Sucre' },
  { isoCode: 'BA', name: 'Bosnia and Herzegovina', capital: 'Sarajevo' },
  { isoCode: 'BW', name: 'Botswana', capital: 'Gaborone' },
  { isoCode: 'BR', name: 'Brazil', capital: 'Brasília' },
  { isoCode: 'BN', name: 'Brunei', capital: 'Bandar Seri Begawan' },
  { isoCode: 'BG', name: 'Bulgaria', capital: 'Sofia' },
  { isoCode: 'BF', name: 'Burkina Faso', capital: 'Ouagadougou' },
  { isoCode: 'BI', name: 'Burundi', capital: 'Gitega' },
  { isoCode: 'CV', name: 'Cabo Verde', capital: 'Praia' },
  { isoCode: 'KH', name: 'Cambodia', capital: 'Phnom Penh' },
  { isoCode: 'CM', name: 'Cameroon', capital: 'Yaoundé' },
  { isoCode: 'CA', name: 'Canada', capital: 'Ottawa' },
  { isoCode: 'CF', name: 'Central African Republic', capital: 'Bangui' },
  { isoCode: 'TD', name: 'Chad', capital: "N'Djamena" },
  { isoCode: 'CL', name: 'Chile', capital: 'Santiago' },
  { isoCode: 'CN', name: 'China', capital: 'Beijing' },
  { isoCode: 'CO', name: 'Colombia', capital: 'Bogotá' },
  { isoCode: 'KM', name: 'Comoros', capital: 'Moroni' },
  { isoCode: 'CG', name: 'Congo', capital: 'Brazzaville' },
  { isoCode: 'CD', name: 'Democratic Republic of the Congo', capital: 'Kinshasa' },
  { isoCode: 'CR', name: 'Costa Rica', capital: 'San José' },
  { isoCode: 'HR', name: 'Croatia', capital: 'Zagreb' },
  { isoCode: 'CU', name: 'Cuba', capital: 'Havana' },
  { isoCode: 'CY', name: 'Cyprus', capital: 'Nicosia' },
  { isoCode: 'CZ', name: 'Czech Republic', capital: 'Prague' },
  { isoCode: 'DK', name: 'Denmark', capital: 'Copenhagen' },
  { isoCode: 'DJ', name: 'Djibouti', capital: 'Djibouti' },
  { isoCode: 'DM', name: 'Dominica', capital: 'Roseau' },
  { isoCode: 'DO', name: 'Dominican Republic', capital: 'Santo Domingo' },
  { isoCode: 'EC', name: 'Ecuador', capital: 'Quito' },
  { isoCode: 'EG', name: 'Egypt', capital: 'Cairo' },
  { isoCode: 'SV', name: 'El Salvador', capital: 'San Salvador' },
  { isoCode: 'GQ', name: 'Equatorial Guinea', capital: 'Malabo' },
  { isoCode: 'ER', name: 'Eritrea', capital: 'Asmara' },
  { isoCode: 'EE', name: 'Estonia', capital: 'Tallinn' },
  { isoCode: 'SZ', name: 'Eswatini', capital: 'Mbabane' },
  { isoCode: 'ET', name: 'Ethiopia', capital: 'Addis Ababa' },
  { isoCode: 'FJ', name: 'Fiji', capital: 'Suva' },
  { isoCode: 'FI', name: 'Finland', capital: 'Helsinki' },
  { isoCode: 'FR', name: 'France', capital: 'Paris' },
  { isoCode: 'GA', name: 'Gabon', capital: 'Libreville' },
  { isoCode: 'GM', name: 'Gambia', capital: 'Banjul' },
  { isoCode: 'GE', name: 'Georgia', capital: 'Tbilisi' },
  { isoCode: 'DE', name: 'Germany', capital: 'Berlin' },
  { isoCode: 'GH', name: 'Ghana', capital: 'Accra' },
  { isoCode: 'GR', name: 'Greece', capital: 'Athens' },
  { isoCode: 'GD', name: 'Grenada', capital: "Saint George's" },
  { isoCode: 'GT', name: 'Guatemala', capital: 'Guatemala City' },
  { isoCode: 'GN', name: 'Guinea', capital: 'Conakry' },
  { isoCode: 'GW', name: 'Guinea-Bissau', capital: 'Bissau' },
  { isoCode: 'GY', name: 'Guyana', capital: 'Georgetown' },
  { isoCode: 'HT', name: 'Haiti', capital: 'Port-au-Prince' },
  { isoCode: 'HN', name: 'Honduras', capital: 'Tegucigalpa' },
  { isoCode: 'HU', name: 'Hungary', capital: 'Budapest' },
  { isoCode: 'IS', name: 'Iceland', capital: 'Reykjavik' },
  { isoCode: 'IN', name: 'India', capital: 'New Delhi' },
  { isoCode: 'ID', name: 'Indonesia', capital: 'Jakarta' },
  { isoCode: 'IR', name: 'Iran', capital: 'Tehran' },
  { isoCode: 'IQ', name: 'Iraq', capital: 'Baghdad' },
  { isoCode: 'IE', name: 'Ireland', capital: 'Dublin' },
  { isoCode: 'IL', name: 'Israel', capital: 'Jerusalem' },
  { isoCode: 'IT', name: 'Italy', capital: 'Rome' },
  { isoCode: 'JM', name: 'Jamaica', capital: 'Kingston' },
  { isoCode: 'JP', name: 'Japan', capital: 'Tokyo' },
  { isoCode: 'JO', name: 'Jordan', capital: 'Amman' },
  { isoCode: 'KZ', name: 'Kazakhstan', capital: 'Astana' },
  { isoCode: 'KE', name: 'Kenya', capital: 'Nairobi' },
  { isoCode: 'KI', name: 'Kiribati', capital: 'South Tarawa' },
  { isoCode: 'KP', name: 'North Korea', capital: 'Pyongyang' },
  { isoCode: 'KR', name: 'South Korea', capital: 'Seoul' },
  { isoCode: 'KW', name: 'Kuwait', capital: 'Kuwait City' },
  { isoCode: 'KG', name: 'Kyrgyzstan', capital: 'Bishkek' },
  { isoCode: 'LA', name: 'Laos', capital: 'Vientiane' },
  { isoCode: 'LV', name: 'Latvia', capital: 'Riga' },
  { isoCode: 'LB', name: 'Lebanon', capital: 'Beirut' },
  { isoCode: 'LS', name: 'Lesotho', capital: 'Maseru' },
  { isoCode: 'LR', name: 'Liberia', capital: 'Monrovia' },
  { isoCode: 'LY', name: 'Libya', capital: 'Tripoli' },
  { isoCode: 'LI', name: 'Liechtenstein', capital: 'Vaduz' },
  { isoCode: 'LT', name: 'Lithuania', capital: 'Vilnius' },
  { isoCode: 'LU', name: 'Luxembourg', capital: 'Luxembourg City' },
  { isoCode: 'MG', name: 'Madagascar', capital: 'Antananarivo' },
  { isoCode: 'MW', name: 'Malawi', capital: 'Lilongwe' },
  { isoCode: 'MY', name: 'Malaysia', capital: 'Kuala Lumpur' },
  { isoCode: 'MV', name: 'Maldives', capital: 'Malé' },
  { isoCode: 'ML', name: 'Mali', capital: 'Bamako' },
  { isoCode: 'MT', name: 'Malta', capital: 'Valletta' },
  { isoCode: 'MH', name: 'Marshall Islands', capital: 'Majuro' },
  { isoCode: 'MR', name: 'Mauritania', capital: 'Nouakchott' },
  { isoCode: 'MU', name: 'Mauritius', capital: 'Port Louis' },
  { isoCode: 'MX', name: 'Mexico', capital: 'Mexico City' },
  { isoCode: 'FM', name: 'Micronesia', capital: 'Palikir' },
  { isoCode: 'MD', name: 'Moldova', capital: 'Chișinău' },
  { isoCode: 'MC', name: 'Monaco', capital: 'Monaco' },
  { isoCode: 'MN', name: 'Mongolia', capital: 'Ulaanbaatar' },
  { isoCode: 'ME', name: 'Montenegro', capital: 'Podgorica' },
  { isoCode: 'MA', name: 'Morocco', capital: 'Rabat' },
  { isoCode: 'MZ', name: 'Mozambique', capital: 'Maputo' },
  { isoCode: 'MM', name: 'Myanmar', capital: 'Naypyidaw' },
  { isoCode: 'NA', name: 'Namibia', capital: 'Windhoek' },
  { isoCode: 'NR', name: 'Nauru', capital: 'Yaren' },
  { isoCode: 'NP', name: 'Nepal', capital: 'Kathmandu' },
  { isoCode: 'NL', name: 'Netherlands', capital: 'Amsterdam' },
  { isoCode: 'NZ', name: 'New Zealand', capital: 'Wellington' },
  { isoCode: 'NI', name: 'Nicaragua', capital: 'Managua' },
  { isoCode: 'NE', name: 'Niger', capital: 'Niamey' },
  { isoCode: 'NG', name: 'Nigeria', capital: 'Abuja' },
  { isoCode: 'MK', name: 'North Macedonia', capital: 'Skopje' },
  { isoCode: 'NO', name: 'Norway', capital: 'Oslo' },
  { isoCode: 'OM', name: 'Oman', capital: 'Muscat' },
  { isoCode: 'PK', name: 'Pakistan', capital: 'Islamabad' },
  { isoCode: 'PW', name: 'Palau', capital: 'Ngerulmud' },
  { isoCode: 'PA', name: 'Panama', capital: 'Panama City' },
  { isoCode: 'PG', name: 'Papua New Guinea', capital: 'Port Moresby' },
  { isoCode: 'PY', name: 'Paraguay', capital: 'Asunción' },
  { isoCode: 'PE', name: 'Peru', capital: 'Lima' },
  { isoCode: 'PH', name: 'Philippines', capital: 'Manila' },
  { isoCode: 'PL', name: 'Poland', capital: 'Warsaw' },
  { isoCode: 'PT', name: 'Portugal', capital: 'Lisbon' },
  { isoCode: 'QA', name: 'Qatar', capital: 'Doha' },
  { isoCode: 'RO', name: 'Romania', capital: 'Bucharest' },
  { isoCode: 'RU', name: 'Russia', capital: 'Moscow' },
  { isoCode: 'RW', name: 'Rwanda', capital: 'Kigali' },
  { isoCode: 'KN', name: 'Saint Kitts and Nevis', capital: 'Basseterre' },
  { isoCode: 'LC', name: 'Saint Lucia', capital: 'Castries' },
  { isoCode: 'VC', name: 'Saint Vincent and the Grenadines', capital: 'Kingstown' },
  { isoCode: 'WS', name: 'Samoa', capital: 'Apia' },
  { isoCode: 'SM', name: 'San Marino', capital: 'San Marino' },
  { isoCode: 'ST', name: 'Sao Tome and Principe', capital: 'São Tomé' },
  { isoCode: 'SA', name: 'Saudi Arabia', capital: 'Riyadh' },
  { isoCode: 'SN', name: 'Senegal', capital: 'Dakar' },
  { isoCode: 'RS', name: 'Serbia', capital: 'Belgrade' },
  { isoCode: 'SC', name: 'Seychelles', capital: 'Victoria' },
  { isoCode: 'SL', name: 'Sierra Leone', capital: 'Freetown' },
  { isoCode: 'SG', name: 'Singapore', capital: 'Singapore' },
  { isoCode: 'SK', name: 'Slovakia', capital: 'Bratislava' },
  { isoCode: 'SI', name: 'Slovenia', capital: 'Ljubljana' },
  { isoCode: 'SB', name: 'Solomon Islands', capital: 'Honiara' },
  { isoCode: 'SO', name: 'Somalia', capital: 'Mogadishu' },
  { isoCode: 'ZA', name: 'South Africa', capital: 'Pretoria' },
  { isoCode: 'SS', name: 'South Sudan', capital: 'Juba' },
  { isoCode: 'ES', name: 'Spain', capital: 'Madrid' },
  { isoCode: 'LK', name: 'Sri Lanka', capital: 'Sri Jayawardenepura Kotte' },
  { isoCode: 'SD', name: 'Sudan', capital: 'Khartoum' },
  { isoCode: 'SR', name: 'Suriname', capital: 'Paramaribo' },
  { isoCode: 'SE', name: 'Sweden', capital: 'Stockholm' },
  { isoCode: 'CH', name: 'Switzerland', capital: 'Bern' },
  { isoCode: 'SY', name: 'Syria', capital: 'Damascus' },
  { isoCode: 'TW', name: 'Taiwan', capital: 'Taipei' },
  { isoCode: 'TJ', name: 'Tajikistan', capital: 'Dushanbe' },
  { isoCode: 'TZ', name: 'Tanzania', capital: 'Dodoma' },
  { isoCode: 'TH', name: 'Thailand', capital: 'Bangkok' },
  { isoCode: 'TL', name: 'Timor-Leste', capital: 'Dili' },
  { isoCode: 'TG', name: 'Togo', capital: 'Lomé' },
  { isoCode: 'TO', name: 'Tonga', capital: "Nuku'alofa" },
  { isoCode: 'TT', name: 'Trinidad and Tobago', capital: 'Port of Spain' },
  { isoCode: 'TN', name: 'Tunisia', capital: 'Tunis' },
  { isoCode: 'TR', name: 'Turkey', capital: 'Ankara' },
  { isoCode: 'TM', name: 'Turkmenistan', capital: 'Ashgabat' },
  { isoCode: 'TV', name: 'Tuvalu', capital: 'Funafuti' },
  { isoCode: 'UG', name: 'Uganda', capital: 'Kampala' },
  { isoCode: 'UA', name: 'Ukraine', capital: 'Kyiv' },
  { isoCode: 'AE', name: 'United Arab Emirates', capital: 'Abu Dhabi' },
  { isoCode: 'GB', name: 'United Kingdom', capital: 'London' },
  { isoCode: 'US', name: 'United States', capital: 'Washington, D.C.' },
  { isoCode: 'UY', name: 'Uruguay', capital: 'Montevideo' },
  { isoCode: 'UZ', name: 'Uzbekistan', capital: 'Tashkent' },
  { isoCode: 'VU', name: 'Vanuatu', capital: 'Port Vila' },
  { isoCode: 'VE', name: 'Venezuela', capital: 'Caracas' },
  { isoCode: 'VN', name: 'Vietnam', capital: 'Hanoi' },
  { isoCode: 'YE', name: 'Yemen', capital: "Sana'a" },
  { isoCode: 'ZM', name: 'Zambia', capital: 'Lusaka' },
  { isoCode: 'ZW', name: 'Zimbabwe', capital: 'Harare' },
];

async function main() {
  console.log('Seeding countries...');
  for (const country of countries) {
    await prisma.country.upsert({
      where: { isoCode: country.isoCode },
      update: {},
      create: country,
    });
  }
  console.log(`Done — ${countries.length} countries seeded.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
